# Generated by Django 3.1.1 on 2020-10-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innertransaction',
            old_name='accout_to',
            new_name='account_to',
        ),
    ]
