# Generated by Django 3.1.1 on 2020-10-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201016_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensetransaction',
            old_name='commentaty',
            new_name='commentary',
        ),
        migrations.RenameField(
            model_name='incometransaction',
            old_name='commentaty',
            new_name='commentary',
        ),
        migrations.RenameField(
            model_name='innertransaction',
            old_name='commentaty',
            new_name='commentary',
        ),
    ]
